name: pytorch-CycleGAN-and-pix2pix
channels:
- defaults
- pytorch
- peterjc123
dependencies:
- python
- pytorch
- scipy
- pip
- pip:
  - dominate
# - git+https://github.com/pytorch/vision.git
  - torchvision
  - Pillow
  - numpy
  - visdom==0.1.7
