name: pytorch-CycleGAN-and-pix2pix
channels:
- peterjc123
- defaults
- conda-forge
- pytorch
dependencies:
#- python=3.5.5
- python
- pytorch=0.4.1
- scipy
- tqdm
- pip
- pip:
  - dominate==2.3.1
  - torchvision
  - Pillow==5.0.0
  - numpy
  - visdom==0.1.7

- imgaug
- albumentations
